### ISSUE TITLE
Wiki activation

### ISSUE THREAD

**Issue by kikito** [somerandomdude/Iconic#1]
Hi somerandomdude,

I've successfully used Iconic on [this opensource redmine theme](https://github.com/splendeo/ohwr-theme).

Although I've given you credit on the readme, I think it would be nice to be able to add a "who uses Iconic" wiki page on this project, similar to the [jekyll sites page](https://github.com/mojombo/jekyll/wiki/Sites).

So, when/if you release Iconic here, and if you like my suggestion, please activate the wiki module.

In any case, thanks for the wonderful lib!

Regards!

**Comment by somerandomdude** [comment]
The Wiki is now activated.
