### ISSUE TITLE
Add .woff format please

### ISSUE THREAD

**Issue by MoOx** [somerandomdude/Iconic#10]
It will be great if the woff format will be included by default !
Thanks for your work anyway !

**Comment by somerandomdude** [comment]
Great idea. I'll get on that this week.

**Comment by somerandomdude** [comment]
.woff files have been added to the latest commit. Thanks for the suggestion!

**Comment by MoOx** [comment]
Yayyy !

**Comment by lucasmazza** [comment]
Just a head's up, I think that the .zip available at http://somerandomdude.com/work/iconic/ doesn't ship with the .woff files. Would be great to update that package too.

**Comment by somerandomdude** [comment]
Thanks Lucas, I'm fixing this right now.
