### ISSUE TITLE
generating json files

### ISSUE THREAD

**Issue by krisbulman** [somerandomdude/Iconic#12]
How are you generating the json files required by the python scripts?

**Comment by somerandomdude** [comment]
Right now, it's manual. I can't think of any _good_ way to automate the process. I was considering using the JSX files which generate PNGs and SVGs from the source Illustrator file to write the JSON files, but there still needs to be a Unicode mapping to each icon at some point in the process - and that can never be automated. If you have any thoughts on the process, I would love to hear them.
