### ISSUE TITLE
Tips for running scripts on OSX

### ISSUE THREAD

**Issue by krisbulman** [somerandomdude/Iconic#13]
- Install homebrew
  
  https://github.com/mxcl/homebrew/wiki/installation
- run the following command
  
  $ brew install fontforge
- If you have trouble, see the following ticket: 
  
  https://github.com/mxcl/homebrew/pull/10714#issuecomment-4500044
- homebrew does not install the py extensions for fontforge, but it does build an with embedded python interpreter. To run a script using homebrew's python interpreter, use the following command
  
  $ fontforge -script whatever.py

**Comment by somerandomdude** [comment]
Thank you sir! Would you mind if I added this to the wiki?

**Comment by krisbulman** [comment]
sure thing, environments may differ, so i will update it as i install it on other boxes

**Comment by andyvanee** [comment]
Works for me as well, though I arrived at the same solution via this thread:

https://github.com/Lokaltog/vim-powerline/issues/13

`fontforge -script iconic_stroke.py`

**Comment by somerandomdude** [comment]
This is good to hear. For some reason, it didn't work for me, I need to do a little more research as to why that was the case.
