### ISSUE TITLE
Stroke star

### ISSUE THREAD

**Issue by jasny** [somerandomdude/Iconic#15]
The star character in the iconic stroke set is currently a filled star. It would be nice if that was a stroked star.

**Comment by somerandomdude** [comment]
Given the style guide of Iconic, a stroked star is literally impossible. I would need to change the weight of the stroke for that one icon and I think that would cause more problems than it would solve. I don't think there will be a stroked star in Iconic, but it will definitely show up in any new icon set I design.

**Comment by jasny** [comment]
_slightly disapointed_

B.t.w. check out iconic in my extended version of bootstrap: http://jasny.github.com/bootstrap/base-css.html#iconic

Unfortunately this probably won't make it into the original project, because most votes go out to FontAwsome :/. https://github.com/twitter/bootstrap/issues/966

**Comment by somerandomdude** [comment]
Hey man, your work looks great!

FontAwesome is a great icon set and probably a better fit for Bootstrap. Iconic was designed for some very specific purposes (a large range of legibility, usually down to 8 pixels) and a über minimal style (often too minimal) based on an 8x8 grid system. This limits what icons I can make and how I can make them.

That said, I am _highly_ considering making a new icon set without those tight restrictions and just go for aesthetics. I feel very confident that I could provide a top-tier icon set that would be a good fit for something like Bootstrap. I am seriously mulling it, I just need the time and resources to make it happen.
