### ISSUE TITLE
Consider namespacing css classes?

### ISSUE THREAD

**Issue by ghost** [somerandomdude/Iconic#18]
Very common class names can cause unintended content insertions at times.  For instance, the Wordpress template function `body_class()` inserts a `.home` class on the homepage's `body` tag.  Using the Iconic font as is will insert the designated character before any body content.

Maybe it might be a good idea to declare icon classes as something like like `.icon-home`, or `.iconic.home` (has it's own "old IE" problems, though)?  It's easy enough to change the classes yourself or even override any problems `body.home:before {content: ""}`.  But, I thought I'd bring it up in case it hadn't been considered yet.

**Comment by borisrorsvort** [comment]
+1

**Comment by somerandomdude** [comment]
I will be working on this soon. Apologies for the radio silence.

**Comment by somerandomdude** [comment]
Great call on this guys. The latest commit addresses this issue.

**Comment by bryceadams** [comment]
Didn't want to open a new issue for this but I was thinking why not just change it so instead of:
`.book_alt2:before {content:'\e049';}` **or** `.iconic-book_alt2:before {content:'\e049';}`
it be made:
`.iconic.book_alt2:before {content:'\e049';}`
as the .iconic class is required regardless.

Any thoughts on this? I personally find it to be much more useful.

**Comment by somerandomdude** [comment]
Yeah, that makes good sense. I'll see if I can fix that in the coming days.

**Comment by bryceadams** [comment]
If you'd like I can make a pull request with the changes already made?  

## 

Bryce Adams

**Comment by somerandomdude** [comment]
Well, I'd like to change the scripts that generate the CSS. If you'd be up for making those changes as well, I wouldn't stand in your way. :)

**Comment by bryceadams** [comment]
Probably best you do it then :)
