### ISSUE TITLE
Broken SVG (bad header)

### ISSUE THREAD

**Issue by puzrin** [somerandomdude/Iconic#19]
I've got report in fontello, that generated SVG must have header `<svg xmlns="http://www.w3.org/2000/svg">` instead of  just `<svg>`. Or webkit (chrome/chromium) can't use such fonts.

https://github.com/fontello/fontello/issues/53

Your fonts have the same problem. Please, fix.

**Comment by somerandomdude** [comment]
Damn. Thanks for the heads up.

P.J.

**Comment by somerandomdude** [comment]
To be honest, my bandwidth is not too open at this point. I can't guarantee when I'll get to this. If you would like to go about fixing this issue, by all means, feel free to do whatever is necessary.

**Comment by puzrin** [comment]
https://github.com/fontello/font-builder/commit/a747402df01688af3f201dc1e07bc27479525352 that was fix for my scripts. It should be ok for you with minimal changes.

Don't know, if you are interested. I think it would be more effective to cleanup your repo - remove raster deals (as rarely used) & switch scripts to `font-builder`. Then i'll be able to effectively maintain your font (as i do for Entypo). Result will be like this https://github.com/fontello/iconic-uni.font , but with separate filled/stroke & old mapping, if those are important for you.

**Comment by somerandomdude** [comment]
This should be fixed now - sorry for the slow turn around.
