### ISSUE TITLE
Please add a print icon

### ISSUE THREAD

**Issue by gr2m** [somerandomdude/Iconic#2]
I'd love to use the font for  a project of mine, but one essential icon is missing: print.

Any chance you could add that?

**Comment by somerandomdude** [comment]
I've been trying to design a print icon for quite some time with little success. I'll continue to try.

**Comment by gr2m** [comment]
I don't know much about Icon design, but I like how the print Icon from Raphael Icon-Set is made
http://icons.marekventur.de/

Cheers
