### ISSUE TITLE
Optimize PNGs

### ISSUE THREAD

**Issue by roxeteer** [somerandomdude/Iconic#20]
When running the PNGs through ImageOptim (a Mac OS X app that uses several different *nix image optimizers), you can easily shave 20-30% from the file size. I can optimize the current images for you and make a pull request, but I guess the optimization should be incorporated to your build process somehow.

**Comment by somerandomdude** [comment]
You bring up a good point. I could possibly add an optimization script - I'd just need to find an elegant way to add that to the collection.

**Comment by somerandomdude** [comment]
I finally got around to fixing this. The latest commit has PNG optimization tools added.
