### ISSUE TITLE
Font Properties - Name missing

### ISSUE THREAD

**Issue by rSSi** [somerandomdude/Iconic#21]
Hi.
I love your font, but it has no Font-Name set in it's properties:
Full-Font-Name and Font-Family are set to "Untitled" in the ttf-version.
I haven't checked the other files yet.

**Comment by somerandomdude** [comment]
Thanks! I'll fix this in future versions.

**Comment by somerandomdude** [comment]
This should be fixed now. Let me know if it works for you.

**Comment by rSSi** [comment]
Thanks! I tried the *.ttf and it works.
