### ISSUE TITLE
Iconic Fill 'cross' & 'check' characters are flipped

### ISSUE THREAD

**Issue by DaanBroekhof** [somerandomdude/Iconic#22]
crosses are checks, and vice versa.

(example unicode range: http://dev.networkerror.org/utf8/?start=10003&end=10008&cols=1&search=&show_uni_int=on&show_uni_hex=on)

You seem to have said that this was fixed in https://github.com/somerandomdude/Iconic/issues/6, but the current font file is still incorrect. (tested iconic_fill.ttf from the master branch just now)

**Comment by somerandomdude** [comment]
This is finally fixed in the latest commit. Thanks for the patience.
