### ISSUE TITLE
Turning all raster icons into CSS3?

### ISSUE THREAD

**Issue by ghost** [somerandomdude/Iconic#24]
Hi, I really like your icon set and thought that it would be a good idea to convert those icons (32x32 rasters) into CSS3. An example of this is at http://jsbin.com/ivonof/1.

Some people (me) don't want to use images nor fonts but do everything in code. I found a neat "[Image to CSS3](http://romainberger.com/lab/image-to-css3/)" converter and thought I'd convert some of your icons. It turned out pretty well. _Of course, this will never be the same great quality as images or fonts (although with higher dimension [say... 64x64 or 128x128] it might be good enough quality, however it will still be as pixelated as an image when zoomed in; icon fonts don't do that). Another disadvantage of CSS3 Icons is the resizability, or rather the lack of it; once you convert an image into CSS3 it stays that way, I don't think there is any way to resize it. Both rasters and fonts obviously have that ability. BUT; I made a little study and it seems like CSS3 Icons are faster than raster icons or font icons. [Check it out here](https://docs.google.com/presentation/d/1b3JzxQ4lH8syC4tiT49-qnsuzwUoej90xIHNKVEL_Ds/edit)._

Hope this helps.

Rafal Chmiel, [rafalchmiel.com](http://rafalchmiel.com/)

**Comment by somerandomdude** [comment]
Hey Rafal, I'm sorry - I didn't see your message until now. Apologies. I've been working on something along those lines - I should have something significant to show in the coming weeks/months.

**Comment by ghost** [comment]
Hi, no problem. Glad to hear it. Have a nice day!
