### ISSUE TITLE
File naming issues

### ISSUE THREAD

**Issue by sb8244** [somerandomdude/Iconic#27]
I tried to fork and fix this myself, but wasn't able to. In raster\gray_dark the arrow_down_alt2 images are actually arrow_up_alt2 and arrow_up_alt2 is actually arrow_down_alt2 (they're flipflopped in names). It appears to be this way for all raster colors.

**Comment by somerandomdude** [comment]
I'll fix that today.

**Comment by somerandomdude** [comment]
All fixed, thanks for catching it!
