### ISSUE TITLE
How to create a custom font with a subset of the icons?

### ISSUE THREAD

**Issue by gr2m** [somerandomdude/Iconic#3]
Is there anyway I could create an own font based on the SVG vector graphics, with only the icons used by my app? That would reduce the file size quite a bit.

**Comment by somerandomdude** [comment]
Agreed. If you look at markup within the SVG file, you'll see a series of _glyph_ elements with a _unicode_ attribute. You could reverse engineer what each glyph is bound to and remove the ones you don't need. It's a hack, but it should work.
