### ISSUE TITLE
Use 2 classes for icon

### ISSUE THREAD

**Issue by phuongnd08** [somerandomdude/Iconic#33]
The way font-awesome works is to use 2 classes to describe an icon. A class for common properties, named `fa` and a class for the content (which varies per icon), named `fa-icon-name`. I think this makes the css itself a bit shorter. And shorter selector get evaluated quicker.

**Comment by somerandomdude** [comment]
Hi there! This project is going to be closing soon and has moved to https://github.com/iconic/open-iconic. Hope this helps!
