### ISSUE TITLE
Hardware Icons?

### ISSUE THREAD

**Issue by cwysong85** [somerandomdude/Iconic#35]
Hello, I've been a supporter of Iconic ever since you launched the Kickstarter project. I was curious if you have plans of putting Database icons, server icons, routers, etc.. I do a lot of enterprise web applications and we have quite a few icons that are hardware related.

**Comment by somerandomdude** [comment]
Hi @cwysong85, apologies for the late response. We've added a Database icon in version 1.4.0 and plan to add a Server icon really soon (perhaps even in the next version).

Thanks!
