### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by levraipixel** [somerandomdude/Iconic#4]
Hi,

Your font is really great, I'm using it right now for my new website !!
But I have a problem: some svg icons that are in the "vector" folder are not set in the font files. Could you explain me how to add them or maybe do it yourself if it's faster and update this git dep ?
That would be awesome !!!

-- Yann

**Comment by somerandomdude** [comment]
Hey Yann, I was planning on adding all the fonts, but unfortunately it is such a considerable pain that I have decided to drop it. I would love to see someone else take this piece on - if you're interested, I'd be happy to lend assistance.

**Comment by levraipixel** [comment]
I hope I can help you.
How did you do it the first time? (which soft, etc)
Do you know how to convert a svg font into all others formats ? I think generating the svg font is quite easy since it is made of very simple XML-like code. I could create a script that creates that file from scratch with little pain, but then I have no idea how to convert it into ttf and other formats...

**Comment by somerandomdude** [comment]
Hey Yann,

I used font creation software which does not do a good job at all.

I do know how to convert a font from SVG to all the main formats - I can
handle that. If you can create that script, I will help you in any way you
need - it would be a tremendous help! I would like to add the script to the
Git repository if you wouldn't mind.

I also planned on following a different organization for which Unicode
positions to use based on the following article:
http://www.codestyle.org/css/at-font-face/StandardUnicodeIconsWebFonts.shtml.
I would be happy to do some of the dirty work if it makes your life
easier.

I have a lot of ideas around this space and would love to work with you on
a couple other ideas if you're interested. I would like to create a
Javascript version of Iconic which allows the rendering of icons in Canvas
and/or WebGL. I have been stymied by my inability to create a script to
convert SVG paths to Javascript code. There is a lot of work in this space,
but nothing that was directly translatable. If you're interested in that, I
would be happy to provide a modest compensation for your work.

I'm eager to hear back from you.

On Wed, Dec 7, 2011 at 6:49 AM, Yann Hourdel <
reply@reply.github.com

**Comment by levraipixel** [comment]
Ok I'll try the script as soon as I can. Should I fork your repository ? Or would you prefer to add me as a collaborator ?

About the unicode idea: I think it would be a good thing, and the modification is very easy to make in the SVG file.

About the JS idea: I think I can help you on this one too, but not right now 'cause I'm in quite a hurry in my current project. But when it's done I'll have a look at it.

About the compensation: the right to use this font will be more than enough ;-)

I'll come back to you as soon as I have tried the script (maybe tonight).

**Comment by somerandomdude** [comment]
Sounds awesome. Let's fork it for now and change it roles as it become necessary. 

This is wonderful, I will make sure to provide significant credit to you.
