### ISSUE TITLE
Consider generate IconicAll font (IconicFill+IconicStroke)

### ISSUE THREAD

**Issue by puzrin** [somerandomdude/Iconic#8]
Division symbols for IconicFill / IconicStroke seems artificial (in my humble opinion). Those differs in 15% symbols only. I can imagine, when it can be useful, but most cases in real life will require both. So, it would be nice to have all symbols in one file. Named as Iconic / IconicAll or smth similar.

**Comment by somerandomdude** [comment]
The reason why they're broken up is that each icon is bound to a matching Unicode character. Having the same icon on a different Unicode character screws things up dramatically. However, please feel free to make a new font generation script that includes all icons in one font set.

**Comment by puzrin** [comment]
I've started remapping, and noticed, that your statement about matching original symbols is not enougth correct.

https://github.com/somerandomdude/Iconic/blob/master/scripts/font%20creation/iconic_fill.json#L34

75% of your symbols are mapped to Private Use Area (E000+). Only 25% have ~ correct equivalent.

**Comment by somerandomdude** [comment]
A lot of those symbols match to a Unicode equivalent in a very high range. There are a ton of un-implemented Unicode glyphs up in the high ranges.
