### ISSUE TITLE
The EOT file appears to be broken

### ISSUE THREAD

**Issue by matiaskorhonen** [somerandomdude/Iconic#9]
The Iconic EOT file appears to be broken on all IEs (as far as I can tell):

<div class="thumbnail"><a href="https://skitch.com/k33l0r/8fuux/dashboard-browserstack"><img style="max-width:638px" src="https://img.skitch.com/20120228-j3isx88qid5u3aq77tqdfjn47u.medium.jpg" alt="Dashboard - BrowserStack" /></a></div>

It doesn't look like it's a CSS syntax issue as I used the "bulletproof" [Fontspring @Font-Face Syntax](http://www.fontspring.com/blog/the-new-bulletproof-font-face-syntax) which has so far worked for every other webfont that I've used.

I prepared a quick demo file to act as a test case: https://github.com/k33l0r/iconic_test_page (works in IE9 due to IE9's TTF/OTF support, broken in IE8 and below).

**Comment by somerandomdude** [comment]
Thanks - I'll look into it this weekend.

**Comment by puzrin** [comment]
There can be 2 problems:
- included HTML demo will not work in IE 6/7, because it uses `:before` to add glyphs
- fontforge can lack of EOT support & write PS1 instead. This header doesn't seems to be EOT:

```
\80l\00\00%!PS-AdobeFont-1.0: IconicFill 001.000
%%Title: IconicFill
%Version: 001.000
%%CreationDate: Thu Dec 29 18:55:15 2011
%%Creator: PJ Onori,,,
%Copyright: Icons by PJ Onori, font creation script by Yann
% Generated by FontForge 20110222 (http://fontforge.sf.net/)
%%EndComments

10 dict begin
/FontType 1 def
/FontMatrix [0.001 0 0 0.001 0 0 ]readonly def
/FontName /IconicFill def
/FontBBox {15 -201 1016 801 }readonly def
/PaintType 0 def
/FontInfo 10 dict dup begin
 /version (001.000) readonly def
 /Notice (Icons by PJ Onori, font creation script by Yann) readonly def
 /FullName (Untitled1) readonly def
 /FamilyName (Untitled1) readonly def
 /Weight (Medium) readonly def
 /FSType 0 def
 /ItalicAngle 0 def
 /isFixedPitch false def
 /UnderlinePosition -100 def
 /UnderlineThickness 50 def
end readonly def
/Encoding StandardEncoding def
currentdict end
currentfile eexec
```

Here is convertor http://code.google.com/p/ttf2eot/

**Comment by matiaskorhonen** [comment]
It's not a CSS/HTML issue; I just recreated the EOT files with `ttf2eot` and those work just fine (in IE8).

I committed the new files to my test repo: k33l0r/iconic_test_page@d044024ecb0b7cdc4d0a626f3e209ddabcc727f3

(though you're right that the test file wouldn't work in IE6/7...)

**Comment by somerandomdude** [comment]
I'm a little conflicted here. I don't want to bloat the HTML/CSS to support outdated browsers. However, I would at least like to provide a working EOT file. I may just replace the EOT and leave it as is. The other option could be to create a separate HTML/CSS file for IE8 and below. Thoughts?

**Comment by puzrin** [comment]
Hm... who cares about HTML/CSS internals, if those are only for testing? Anyway, i'll be fine with any solution, that allow to check, that EOT is really working.

**Comment by matiaskorhonen** [comment]
I **really** don't care if the test page works in IE6/7 as long as the EOT file does (and IE8 _does_ support the `:before` pseudo element).

**Comment by somerandomdude** [comment]
Sorry guys, I missed the "deadline" for this. :) I'm planning on taking care of this tomorrow.

**Comment by somerandomdude** [comment]
OK, I'm WAY late on this issue, but I've committed new EOT files. Unfortunately I don't have a PC to test on - would anyone be willing to give it a shot?

**Comment by francocatena** [comment]
Fill and Stroke now works great to me in Explorer 7 and 8.

**Comment by somerandomdude** [comment]
Awesome! I used FontSquirrel's font generator. Now I just need to figure out why the FontForge Python scripts are not generating usable EOT files...

Thanks for the confirmation!

**Comment by petrchutny** [comment]
It seems like EOT file isn't working again (IE7,8) – while the EOT generated from FontSquirrel (based on the TTF) works fine, BUT I can't manage to include all glyphs – even with no subsetting, the paper glyph is missing for instance.

**Comment by somerandomdude** [comment]
Grrr... OK. I'm kind of at a loss as to what's happening with the EOT file. I'll see what I can do to fix this.

**Comment by petrchutny** [comment]
Thank you kindly, may the force be with you and others who stand up to the god damn IE.

**Comment by underbluewaters** [comment]
I've tried putting the .ttf (both my own build and the own from the packaged download) through fontsquirrel and ttf2eot with no luck :(

**Comment by somerandomdude** [comment]
Is the EOT file not working for you?

**Comment by underbluewaters** [comment]
I wasn't able to get the one in the packaged download to work, or any custom builds. I ended up using Fontello to put together a custom font which works. It took some fiddling with the character mappings though. I wonder if that could have had more to do with it. I'll try to do some tinkering in the morning.

**Comment by somerandomdude** [comment]
Let me know how it works out for you.

**Comment by anthonybruno** [comment]
Having this problem as well. Nothing I do to regenerate an EOT seems to work. Any follow up?

**Comment by somerandomdude** [comment]
I'll look into this tonight/tomorrow.

**Comment by somerandomdude** [comment]
OK

**Comment by somerandomdude** [comment]
Sorry, I accidentally closed this. So I've updated the fonts and I know the EOT file is working. My demo code is not working though and I am still trying to figure out why that's the case. I'll update when I have a solution.

**Comment by petrchutny** [comment]
Good, thanks!

**Comment by somerandomdude** [comment]
No problem! Let me know if you have any issues.
